### ISSUE TITLE
Adjusting content structure

### ISSUE THREAD

**Issue by amirhouieh** [acid-info/design-assets#2]
We want to use Wiki for documentation and use repo only for hosting assets. So in other words you should remove all `<BU>.md` files in the root directory of the repo and keep the folders only.

**Comment by jinhojang6** [comment]
Okay. Let me remove the markdown files in the next PR.

**Comment by jinhojang6** [comment]
Updated it in the new PR : https://github.com/acid-info/design-assets/pull/9
